
test_code:
  image: rootproject/root-ubuntu16:6.12
  stage: test
  before_script:
    - mkdir -p $HOME/.local
    - curl -s "https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C $HOME/.local
    - export PATH=$HOME/.local/bin:$PATH
  script:
    - mkdir -p build
    - cd build
    - cmake ../examples
    - cmake --build .
    - ctest
    - cd ..

pages:
  image: node:carbon
  stage: deploy
  only:
    - master
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install gitbook-cli -g #
    - gitbook fetch latest
    - gitbook install
  script:
    - gitbook build . public
  artifacts:
    paths:
      - public
    expire_in: 1 week

